### ISSUE TITLE
Git import script can't pull multiple repos into the same directory 

### ISSUE THREAD

**Issue by mchurichi** [spiffe/spiffe.io#193]
As it is right now, if we want to use the [pull_external script ](https://github.com/spiffe/spiffe.io/blob/master/pull_external.py)to import files from different repositories into the same directory, it is not possible because the yaml we need to do it will have duplicated keys (`spire-docs` in the example). The last occurrence of the key will override all the previous occurrences.

For example, this yaml will only pull `JWT-SVID.md`:
```yaml
spire-docs:
    source: https://github.com/spiffe/spire
    pullFiles:
        - doc/upgrading.md
spire-docs:
    source: https://github.com/spiffe/spiffe
    pullFiles:
        - standards/JWT-SVID.md
```
